### ISSUE TITLE
Leaders can "save"/favorite applicants

### ISSUE THREAD

**Issue by cherrybeans** [webkom/committee-admissions-webapp#18]
It might be easier for them to keep track of who they will contact or are considering

**Comment by ekmartin** [comment]
I don't think this is needed, as each committee has their own way of managing candidates. We, for example, have usually kept candidates in a shared spreadsheet, and assigned them different colors based on viability. The spreadsheet also includes other information: comments and so on. I think it would be quite out of scope to embed much of the same functionality into the admissions website (also, everyone in the committee would need access—not just the leaders!).

A good compromise would probably be to implement some sort of export functionality instead, where all of the information we know about an applicant (and the application) would result in a row in a Google Spreadsheet. Then each committee could add other information to the spreadsheet as they see fit. This is still a stretch goal though—maybe for another year?

**Comment by cherrybeans** [comment]
Good arguments, and I completely agree :+1:
